version: '2'
services:
  mailman:
    image: thelinuxguy/mailman
    volumes:
      - ./mailman_config:/home/mailman/var
  postorius:
    image: thelinuxguy/postorius
    environment:
      - MAILMAN_REST_API_URL=http://mailman-core:8001
      - MAILMAN_REST_API_USER=restadmin
      - MAILMAN_REST_API_PASS=restpass
    links:
      - mailman:mailman-core
    volumes:
      - ./postorius_config:/postorius/local
    ports:
      - 8000:8000
